apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: production
  name: vertere-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vertere-web
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
